modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"

[[mods]]
modId = "haproxy-support"
version = "${version}"
displayName = "HAProxy Support"

[[dependencies.haproxy-support]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.haproxy-support]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
